feat: support to rename and delete tag
alibaba/loongcollector pull request #1806
Opened 2024-10-14 11:28 UTC by Abingcbc

2024-10-21 09:00 UTC, henryzhx8 requested changes

2024-10-21 09:00 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +#endif
这个地方看起来可以优化一下，但暂时没想到好办法

2024-10-21 09:00 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
>          Json::Value& global = pipeline["global"];
这里优化一下吧，这个Copy函数不要从pipeline去调用了，把initglobal函数增加两个入参，就是两个gopipeline，直接在那个里面添加，这样global config里根本不需要存这些参数了，这些参数所有权本来就在tag插件里

2024-10-21 09:00 UTC, henryzhx8 commented on core/plugin/processor/inner/ProcessorTagNative.cpp
整体实现需要重新看一下文档

2024-10-21 09:00 UTC, henryzhx8 commented on core/runner/ProcessorRunner.cpp
> +        logTag->set_value(tag.second.to_string());
这里不用改

2024-10-21 09:00 UTC, henryzhx8 commented on pkg/helper/docker_center.go
不用改

2024-10-21 09:00 UTC, henryzhx8 commented on pluginmanager/plugin_runner_helper.go
>  func loadAdditionalTags(globalConfig *config.GlobalConfig) models.Tags {
这个函数还需要？

2025-01-08 11:27 UTC, Abingcbc commented on core/models/PipelineEventGroup.h
>      LOG_FILE_INODE,
inode要在processor重命名，所有要在reader中将inode信息传递下去

2025-01-08 14:46 UTC, Abingcbc commented on core/pipeline/GlobalConfig.h
> +    bool mEnableAgentEnvMetaTagControl = false;
因为其他参数是空的时候，走默认的行为。但AgentEnvMeta这个是空的时候全部删除。传递给Go的时候，需要能够区分有这个参数为空还是没有这个参数。

2025-01-13 00:54 UTC, messixukejia requested changes

2025-01-13 00:54 UTC, messixukejia commented on core/constants/TagConstants.cpp
> +const std::string DEFAULT_LOG_TAG_HOST_ID = "__host_id__";
都没有调用点

2025-01-13 00:54 UTC, messixukejia commented on core/plugin/processor/ProcessorParseApsaraNative.h
> -    ProcessEvent(const StringView& logPath, PipelineEventPtr& e, LogtailTime& lastLogTime, StringView& timeStrCache);
![image](https://github.com/user-attachments/assets/3bd2cf4a-1810-4619-98c3-c29695f791f6)

这句话意思是要把meta改成content吗？

2025-01-13 01:39 UTC, Abingcbc commented on core/container_manager/ContainerDiscoveryOptions.cpp
> -    res["global"]["AlwaysOnline"] = Json::Value(true);
配置独立热加载之后，AlwaysOnline已经没用了

2025-01-13 01:41 UTC, Abingcbc commented on core/plugin/processor/ProcessorParseApsaraNative.h
> -    ProcessEvent(const StringView& logPath, PipelineEventPtr& e, LogtailTime& lastLogTime, StringView& timeStrCache);
之前改的时候发现字节Go那边很多都是叫metadata，讨论之后决定不改名了。我更新一下文档

2025-01-13 09:35 UTC, henryzhx8 requested changes

2025-01-13 09:35 UTC, henryzhx8 commented on core/plugin/processor/inner/ProcessorTagNative.cpp
> +    addDefaultAddedTag(logGroup, TagKey::HOST_NAME, LoongCollectorMonitor::GetInstance()->mHostname);
C++到go的流水线，应该用C++的还是用Go的内置插件？现在的实现好像只能用go的，而且应该统一由一个地方处理，不应该go和C++都处理一些

2025-01-13 09:35 UTC, henryzhx8 commented on core/plugin/processor/inner/ProcessorTagNative.cpp
> +    }
可以直接调用下面的代码

2025-01-13 09:35 UTC, henryzhx8 commented on core/plugin/processor/inner/ProcessorTagNative.cpp
> +            if (it->second == DEFAULT_CONFIG_TAG_KEY_VALUE) {
这段逻辑应该在init的时候，和input那边一样

2025-01-13 09:35 UTC, henryzhx8 commented on pluginmanager/plugin_runner_v2.go
> +	if !p.LogstoreConfig.GlobalConfig.UsingOldContentTag {
这个为啥以前没有？

2025-01-13 09:35 UTC, henryzhx8 commented on pluginmanager/processor_tag_enterprise.go
这个文件是否应该放到内部仓库？

2025-01-13 09:35 UTC, henryzhx8 commented on pluginmanager/processor_tag_commuinty.go
现有C++和go的tag行为不一致，需要保持一致，而不是继续遵从现状，详见设计文档。

2025-01-14 16:44 UTC, Abingcbc commented on core/file_server/FileTagOptions.h
> +    void parseTagKey(const Json::Value* config,
clang-tidy提示的private的方法应该是小写
![image](https://github.com/user-attachments/assets/2d16cff6-e373-4a4c-9523-11772118f239)

2025-01-16 05:32 UTC, henryzhx8 commented on core/file_server/FileTagOptions.h
> +    void parseTagKey(const Json::Value* config,
不需要服从clang-tidy

2025-01-16 11:01 UTC, henryzhx8 requested changes

2025-01-16 12:14 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +        mInnerProcessorLine.emplace_back(std::move(processor));
x

pipelineinnerprocess
且只有一个

2025-01-16 13:06 UTC, messixukejia commented on core/constants/TagConstants.cpp
> +const string DEFAULT_LOG_TAG_HOST_NAME = "namespace"; // should keep same with metric
开源改成以前的吧

2025-01-16 13:06 UTC, messixukejia commented on core/models/PipelineEventGroup.cpp
> +const string EVENT_GROUP_META_LOG_FILE_OFFSET = "log.file.offset";
先看看能删掉的删了

2025-01-16 13:06 UTC, messixukejia commented on pluginmanager/processor_tag.go
> +	hostNameDefaultTagKey      = "host_name"
这里部分商业开源？

2025-01-17 06:13 UTC, Abingcbc commented on pluginmanager/processor_tag.go
> +	hostNameDefaultTagKey      = "host_name"
这里只有开源的，商业版在另一个文件，单独提交到内部

2025-01-21 02:10 UTC, henryzhx8 requested changes

2025-01-21 02:10 UTC, henryzhx8 commented on core/file_server/ContainerInfo.cpp
> +                    containerInfo.mTags.emplace_back(key, value);
这段逻辑和qiuwencheng确认下，感觉有点怪

2025-01-21 02:10 UTC, henryzhx8 commented on core/file_server/FileTagOptions.cpp
> +#include <unistd.h>
这个有用吗？

2025-01-21 02:30 UTC, messixukejia approved these changes

2025-01-21 02:30 UTC, messixukejia commented on docs/cn/configuration/collection-config.md
> +| HOST_NAME | 是 | host.name |
字段名变了

2025-01-21 02:30 UTC, messixukejia commented on docs/cn/plugins/input/native/input-file.md
> +| FileInodeTagKey | 否 | file_offset |
默认值

2025-01-21 02:30 UTC, messixukejia commented on core/plugin/processor/inner/ProcessorTagNative.cpp
> +        ECSMeta meta = entity->GetECSMeta();
聚合一下 __ENTERPRISE__ 的使用

2025-01-21 02:30 UTC, messixukejia commented on core/plugin/processor/inner/ProcessorTagNative.cpp
> +            if (mAgentEnvMetaTagKey.empty() && mAppendingAllEnvMetaTag) {
AgentEnvMetaTagKey 文档里写下环境变量的来源

2025-01-21 05:50 UTC, Abingcbc commented on core/file_server/ContainerInfo.cpp
> +                    containerInfo.mTags.emplace_back(key, value);
之前代码判断写错了

2025-01-21 11:10 UTC, henryzhx8 approved these changes

2025-01-21 11:10 UTC, henryzhx8 commented on core/constants/TagConstants.h
> +enum TagKey {
enum class

2025-01-22 01:47 UTC, merged