improve sls authentication logic
alibaba/loongcollector pull request #1894
Opened 2024-11-18 08:20 UTC by henryzhx8

2024-11-23 04:52 UTC, yyuuttaaoo requested changes

2024-11-23 04:52 UTC, yyuuttaaoo commented on core/runner/FlusherRunner.cpp
> +                        ("failed to build request", "discard item")("item address", item)(
address? is that helpful? how about log how much data is discarded?

2024-11-23 04:52 UTC, yyuuttaaoo commented on core/sdk/Client.cpp
> +            throw LOGException(LOGE_UNAUTHORIZED, "");
this method should not throw

2024-11-25 02:31 UTC, henryzhx8 commented on core/sdk/Client.cpp
> +            throw LOGException(LOGE_UNAUTHORIZED, "");
这里需要throw，外层函数会catch。现有代码同步调用都是通过throw来返回结果的，这个会在下一个重构client的pr里更改。

2024-11-25 02:31 UTC, henryzhx8 commented on core/runner/FlusherRunner.cpp
> +                        ("failed to build request", "discard item")("item address", item)(
地址是配合debug日志使用的

2024-11-25 02:31 UTC, henryzhx8 commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +bool FlusherSLS::BuildRequest(SenderQueueItem* item, unique_ptr<HttpSinkRequest>& req, bool* keepItem) const {
遵循google style

2024-11-25 02:32 UTC, henryzhx8 commented on core/monitor/profile_sender/ProfileSender.cpp
> +    sdk::Client client("", endpoint, INT32_FLAG(sls_client_send_timeout));
保持现状，下一个重构client的pr会进行整体调整。

2024-11-27 02:56 UTC, yyuuttaaoo approved these changes

2024-11-30 11:44 UTC, messixukejia commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +        LOG_INFO(sLogger,
这个日志会不会在不稳定的时候打印过于频繁

2024-11-30 11:44 UTC, messixukejia commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +#ifdef __ENTERPRISE__
1

2024-12-02 02:33 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +        LOG_INFO(sLogger,
这个是有一定可能的，但是量级上应该比reader的打开关闭要小的多，所以应该还好。可以先观察一下，如果确实量太大，可以再省略。

2024-12-02 03:08 UTC, messixukejia approved these changes

2024-12-02 03:08 UTC, messixukejia commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +        LOG_INFO(sLogger,
降打印，跑一下e2e看看 日志/消息包 的比例

2024-12-02 03:08 UTC, messixukejia commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +#ifdef __ENTERPRISE__
1

2024-12-03 01:32 UTC, merged