feat: add scrape state metrics
alibaba/loongcollector pull request #1900
Opened 2024-11-19 08:52 UTC by catdogpandas

2024-11-19 10:14 UTC, catdogpandas commented
将 libcurl 的原始状态码返回，不要转换为字符串，映射转换为自监控指标，保证可控、枚举性，

2024-11-19 15:36 UTC, xdatcloud commented
Reason 原因需要收敛下，比如我们通常遇到下面错误比较多：
```
● 401 / 403：采集作业需要配置正确的认证信息
● Connection Refused：目标端口未正常建立监听服务，通常服务发现配置出错，将它们排除即可
● Connection Timeout：通常是防火墙策略对探针拒绝访问，需要对探针放开、允许通信
● Request Timeout：采集超时，需调大采集间隔（scrape_interval）与采集超时（scrape_timeout）参数
```
正常情况下 `status=OK`，如果遇到错误可以整理成枚举值 `ERR_CODE_401`, `ERR_CODE_403`, `ERR_CONN_REFUSED` 等等，如果无命中当前枚举的统一用 `status=ERR_UNKNOWN` 处理

2024-11-22 23:06 UTC, linrunqi08 requested changes

2024-11-22 23:06 UTC, linrunqi08 commented on core/common/http/AsynCurlRunner.cpp
> +        request->mResponse.SetCurlCode(CURL_LAST);
![image](https://github.com/user-attachments/assets/391be6b5-152a-43f2-ab8e-8e875e372207)
这里强行设置有什么作用呢？而且CURL_LAST好像没有含义且不推荐使用

2024-11-22 23:06 UTC, linrunqi08 commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +    } else if (response.GetStatusCode() != 200) {
这种通过两个变量分别判断会有问题吧，假设性太强了。要么你就CurlCode和StatusCode在条件判断里

2024-11-25 02:54 UTC, catdogpandas commented on core/common/http/AsynCurlRunner.cpp
> +        request->mResponse.SetCurlCode(CURL_LAST);
因为 CURL_OK 值是0，但是这里明显执行失败了，所以不能为0，而除了 CURL_LAST 的其他非零值都是有意义的，所以用 CURL_LAST。改成了 CURLE_FAILED_INIT。

2024-11-25 03:54 UTC, messixukejia requested changes

2024-11-25 03:54 UTC, messixukejia commented on core/prometheus/PromSelfMonitor.cpp
> +    if (status < 600) {
自监控指标太多了（这里又出来这么多label取值），已经搞不下去了。需要限制，这个你找玄飏再交流下规范，他最近在整改了。

2024-11-25 03:54 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +    } else if (response.GetStatusCode() != 200) {
既然有依赖，为什么不用同一组错误码表示

2024-11-25 04:02 UTC, catdogpandas commented on core/prometheus/PromSelfMonitor.cpp
> +    if (status < 600) {
这里不会增加很多 label 取值，正常运行下只会有 200 这一个取值。label 取值多并不会直接导致时间线发散，只有同时存在 200、3xx、4xx 的情况才会引起自监控指标发散，显然这是不可能的。导致发散的情况是短暂的出现了如 303 状态码，后续恢复正常后，303 状态码的时间线仍在被上报，这种情况是可以检测出来的，Monitor 系统组件或业务组件都可以做这个指标收敛操作。

2024-11-25 09:29 UTC, catdogpandas commented on core/monitor/metric_constants/PluginMetrics.cpp
> +const std::string METRIC_PLUGIN_PROM_SCRAPE_STATE = "prom_scrape_state";
加个功能开关，改为 scrape_state

2024-11-26 01:42 UTC, henryzhx8 commented on core/common/http/HttpResponse.h
> +    int32_t GetCurlCode() { return mCurlCode; }
加这个的原因是什么？

2024-11-28 09:00 UTC, catdogpandas commented
在 4.x 中对应 aliyun_prometheus_agent_scrape_custom_error 指标

2024-11-30 11:55 UTC, messixukejia requested changes

2024-11-30 11:55 UTC, messixukejia commented on core/plugin/processor/inner/ProcessorPromRelabelMetricNative.cpp
> +DEFINE_FLAG_BOOL(enable_scrape_state, "enable scrape_state auto metric", true);
为什么还要引入一个开关？没有特别大必要，尽量避免控制太复杂

2024-11-30 11:55 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +        mScrapeState = ToString(response.GetStatusCode());
response.GetStatusCode() 取值范围是什么

2024-12-02 02:09 UTC, catdogpandas commented on core/plugin/processor/inner/ProcessorPromRelabelMetricNative.cpp
> +DEFINE_FLAG_BOOL(enable_scrape_state, "enable scrape_state auto metric", true);
先删掉了

2024-12-02 02:11 UTC, catdogpandas commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +        mScrapeState = ToString(response.GetStatusCode());
HTTP 状态码，0-600

2024-12-03 01:26 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +        mScrapeState = ToString(response.GetStatusCode());
这三个分支，第一、三个返回字符串，第二个返回数字。感觉并不是很合理。造成同一个状态字段，取值的差异很大。

这种方式是自己想的，还是有出处的参考的。如果自己想的可能得调整下。

2024-12-03 05:44 UTC, messixukejia approved these changes

2024-12-03 06:25 UTC, henryzhx8 approved these changes

2024-12-03 06:25 UTC, henryzhx8 commented on core/common/http/HttpResponse.h
> +struct NetWorkStatus {
NetworkStatus

2024-12-03 06:25 UTC, henryzhx8 commented on core/common/http/HttpResponse.h
> +    TIMEOUT, // 超时
大小写统一

2024-12-03 06:25 UTC, henryzhx8 commented on core/common/http/HttpResponse.h
> +    NetWorkStatus GetNetworkStatus() { return mNetworkStatus; }
const &

2024-12-16 09:55 UTC, linrunqi08 approved these changes

2024-12-16 09:55 UTC, merged