Refactor self-monitor directory structure and remove status_profile
alibaba/loongcollector pull request #1932
Opened 2024-11-28 03:56 UTC by Takuka0311

1. 调整了自监控目录结构，将指标相关的数据结构移到core/monitor/metric_models目录
2. 对LogtailMonitor进行修改，移除了statu_profile

2024-11-28 04:05 UTC, messixukejia approved these changes

2024-11-28 04:07 UTC, messixukejia requested changes

2024-11-28 04:07 UTC, messixukejia commented on core/monitor/Monitor.cpp
> +        && (GetCurrentLogtailTime().tv_sec - lastReadEventTime > AppConfig::GetInstance()->GetForceQuitReadTimeout())) {
1

2024-11-28 07:41 UTC, messixukejia approved these changes

2024-11-29 02:18 UTC, yyuuttaaoo requested changes

2024-11-29 02:18 UTC, yyuuttaaoo commented on core/file_server/polling/PollingDirFile.cpp
> +        mPollingDirCacheSize->Set( mDirCacheMap.size());
多了空格

2024-11-29 02:18 UTC, yyuuttaaoo commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +    metricEventPtr->SetValue({});
这个空的是什么意思

2024-11-29 02:18 UTC, yyuuttaaoo commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +            } catch (...) {
exception是哪个方法抛出的？有没有具体要catch的类型？

2024-11-29 02:18 UTC, yyuuttaaoo commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +        if (itr->isUInt64()) {
下面都没有Unsigned的限制，这个为啥就要有呢？

2024-11-29 02:18 UTC, yyuuttaaoo commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
这个文件完全没有UT覆盖

2024-11-29 02:18 UTC, yyuuttaaoo commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +    ParseJsonTable(metricRecord.at(METRIC_GO_KEY_LABELS), labels, errMsg);
error需要处理吗

2024-12-02 04:00 UTC, Takuka0311 commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +    metricEventPtr->SetValue({});
通过空map初始化UntypedMultiDoubleValues。也可以Set UntypedMultiDoubleValues对象

2024-12-02 04:03 UTC, Takuka0311 commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +            } catch (...) {
std::stod。没有

2024-12-02 04:03 UTC, Takuka0311 commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +    ParseJsonTable(metricRecord.at(METRIC_GO_KEY_LABELS), labels, errMsg);
这里由go传过来的数据，假定都是正确的、不应该有err

2024-12-02 04:03 UTC, Takuka0311 commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
我加一下

2024-12-02 05:33 UTC, Takuka0311 commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +        if (itr->isUInt64()) {
应该都是string，这边有些乱了，已删

2024-12-02 13:54 UTC, yyuuttaaoo commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +    metricEventPtr->SetValue({});
不初始化会有什么问题？能让即使不初始化也没有问题吗

2024-12-02 14:00 UTC, yyuuttaaoo commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +            } catch (...) {
在标准 C++ 库中，std::stod 函数只会抛出两种特定的异常：std::invalid_argument 和 std::out_of_range。根据 C++ 标准，std::stod 的行为是明确的，不会抛出其他类型的异常。
写...兜底没有问题，但不是没有具体类型。
} catch (...) { // catch std::invalid_argument & std::out_of_range

2024-12-03 01:00 UTC, messixukejia commented on core/monitor/metric_models/SelfMonitorMetricEvent.cpp
> +    ParseJsonTable(metricRecord.at(METRIC_GO_KEY_LABELS), labels, errMsg);
任何外部交互都是不可信的，除非是一个文件启动的有上下文。go已经是额外文件了，是存在被换掉的可能

2024-12-03 06:47 UTC, yyuuttaaoo approved these changes

2024-12-03 07:20 UTC, merged