feat: support singleton input
alibaba/loongcollector pull request #1933
Opened 2024-11-28 06:47 UTC by Abingcbc

1. 加载流水线时，对只能存在一个实例的input进行限制
2. 对加载的配置顺序进行排序，保证后续先创建的配置，先加载流水线

2024-11-29 03:09 UTC, henryzhx8 requested changes

2024-11-29 03:09 UTC, henryzhx8 commented on core/pipeline/plugin/PluginRegistry.cpp
> +
加个空行

2024-11-29 03:09 UTC, henryzhx8 commented on core/pipeline/PipelineManager.cpp
> +            && mPluginCntMap["inputs"][inputType] > 0) {
这里判断不对，配置变更的场景，先init再stop老的，这里肯定大于0。不要依赖这个Map，这个map本身以前是用来做自监控的。

2024-11-29 03:09 UTC, henryzhx8 commented on core/pipeline/PipelineManager.h
> +    bool CheckIfGlobalSingletonInputLoaded(std::vector<const Json::Value*>& inputConfig);
这俩函数合一块就行了

2024-11-29 03:09 UTC, henryzhx8 commented on core/pipeline/PipelineManager.cpp
> +        if (!PreCheckPipelineConfig(config)) {
不用在这里特别调用了，直接在buildpipline里面构建input的地方调用就行了

2024-11-29 03:09 UTC, henryzhx8 commented on core/config/watcher/PipelineConfigWatcher.cpp
> +    // sort rule
一个原本运行的配置，创建时间晚，现在变更了；又有一个原本没运行的配置，创建时间早，新加了，预期行为是什么？现在代码符合预期吗？

2024-12-04 03:48 UTC, messixukejia requested changes

2024-12-04 03:48 UTC, messixukejia commented on core/config/PipelineConfig.cpp
> +    if ((hasFileInput || !mSingletonInput.empty()) && (*mDetail)["inputs"].size() > 1) {
感觉还是把判断放上面吧。因为文件这个限制肯定是要去掉的。

可以跟笃敏再确认下

2024-12-04 03:48 UTC, messixukejia commented on core/unittest/config/PipelineConfigWatcherUnittest.cpp
> +void PipelineConfigWatcherUnittest::TestPushPipelineConfig() const {
需要给下测试用例设计，一些边界的组合需要考虑全面

2024-12-04 03:48 UTC, messixukejia commented on core/config/watcher/PipelineConfigWatcher.cpp
> +                if (mPipelineManager->FindConfigByName(it->second->config.mName)) {
如交流生效的处理有问题

2024-12-05 12:20 UTC, messixukejia approved these changes

2024-12-05 12:20 UTC, messixukejia commented on core/config/PipelineConfig.cpp
> +    if ((hasFileInput) && (*mDetail)["inputs"].size() > 1) {
去掉新增的()

2024-12-05 12:22 UTC, messixukejia approved these changes

2024-12-05 12:22 UTC, messixukejia commented on core/unittest/config/PipelineConfigWatcherUnittest.cpp
> +        PrepareConfig();
拆成多个用例

2024-12-05 12:24 UTC, messixukejia commented on core/unittest/config/PipelineConfigWatcherUnittest.cpp
> +            "createTime": 1,
用例里夹杂些非单例场景的干扰

2024-12-10 11:47 UTC, henryzhx8 approved these changes

2024-12-11 01:43 UTC, merged