feat: add internal config provedier
alibaba/loongcollector pull request #1936
Opened 2024-12-02 03:27 UTC by Takuka0311

添加内置流水线获取能力

2024-12-02 06:33 UTC, messixukejia requested changes

2024-12-02 06:33 UTC, messixukejia commented on core/provider/Provider.cpp
> +    return InternalConfigProvider::GetInstance();
为什么还要封装一次

2024-12-02 06:33 UTC, messixukejia commented on core/config/internal_provider/InternalConfigProvider.cpp
> +InternalConfigProvider* InternalConfigProvider::GetInstance() {
没太大必要不要随意的引入单例，尽量在之前的基础上实现

2024-12-02 06:37 UTC, Takuka0311 commented on core/provider/Provider.cpp
> +    return InternalConfigProvider::GetInstance();
这边是为了跟common_config_provider等保持一致，同时复制了profile_sender的模式。我把这一层去掉吧

2024-12-02 06:37 UTC, Takuka0311 commented on core/config/internal_provider/InternalConfigProvider.cpp
> +InternalConfigProvider* InternalConfigProvider::GetInstance() {
好的

2024-12-02 08:21 UTC, Takuka0311 commented on core/config/internal_provider/InternalConfigProvider.cpp
> +InternalConfigProvider* InternalConfigProvider::GetInstance() {
这里还是需要一个类单例来完成任务的，一方面：

1. 需要根据开源版/商业版分别去创建实例
2. 管控内置config的生成，需要保存一些状态，比如在商业版需要保存metric Debug模式是否开启等信息，需要一个持久化的类
3. 作为一个config_provider，从逻辑上来说就应该是单一的、持久化的

2024-12-02 13:18 UTC, messixukejia commented on core/config/internal_provider/InternalConfigProvider.cpp
> +InternalConfigProvider* InternalConfigProvider::GetInstance() {
不赞同，征求下其他人意见吧

2024-12-02 13:50 UTC, yyuuttaaoo requested changes

2024-12-02 13:50 UTC, yyuuttaaoo commented on core/config/watcher/PipelineConfigWatcher.cpp
> +        const string pipelineName = pipeline.first, pipleineDetail = pipeline.second;
这种写2行，用引用

2024-12-02 13:50 UTC, yyuuttaaoo commented on core/config/internal_provider/InternalConfigProvider.cpp
> +InternalConfigProvider* InternalConfigProvider::GetInstance() {
原来的ConfigProvider可以继续用啊，加一个接口

2024-12-03 05:59 UTC, yyuuttaaoo commented on core/config/common_provider/CommonConfigProvider.h
> +    const std::map<std::string, std::string>& GetAllInernalPipelineConfigs();
typo

2024-12-03 06:05 UTC, yyuuttaaoo commented on core/config/watcher/PipelineConfigWatcher.cpp
> +    const std::map<std::string, std::string>& innerPipelines
用GetRemoteConfigProviders获取ConfigProvider

2024-12-03 06:05 UTC, yyuuttaaoo commented on core/config/common_provider/CommonConfigProvider.h
> +    std::map<std::string, std::string> mPipelineMaps;
mPipelineMap

2024-12-03 06:22 UTC, messixukejia commented on core/config/watcher/PipelineConfigWatcher.cpp
> +    const std::map<std::string, std::string>& innerPipelines
del else

2024-12-03 06:22 UTC, messixukejia approved these changes

2024-12-03 06:45 UTC, yyuuttaaoo approved these changes

2024-12-03 07:11 UTC, merged