fix: judge file server changed
alibaba/loongcollector pull request #1970
Opened 2024-12-17 01:53 UTC by Abingcbc

应该是任意一个配置改变了input_file，isFileServerInputChanged都应该是true

2024-12-17 02:48 UTC, yyuuttaaoo approved these changes

2024-12-17 06:04 UTC, messixukejia requested changes

2024-12-17 06:04 UTC, messixukejia commented on core/pipeline/PipelineManager.cpp
> +        string inputType = (*config.mInputs[0])["Type"].asString();
load配置的地方是否能够保证[0]的合法性？

2024-12-18 01:40 UTC, henryzhx8 approved these changes

2024-12-18 03:29 UTC, Abingcbc commented on core/pipeline/PipelineManager.cpp
> +        string inputType = (*config.mInputs[0])["Type"].asString();
前面配置解析会检验input至少包含一个，保证这里加载流水线一定是合法的

2024-12-18 10:13 UTC, messixukejia approved these changes

2024-12-18 16:40 UTC, merged