Optimize the limiter code to meet better isolation and recovery scenarios
alibaba/loongcollector pull request #1985
Opened 2024-12-23 06:11 UTC by linrunqi08

2024-12-24 03:00 UTC, messixukejia requested changes

2024-12-25 02:15 UTC, henryzhx8 approved these changes

2024-12-25 06:36 UTC, linrunqi08 commented on core/plugin/flusher/sls/FlusherSLS.cpp
>          return limiter;
SEND_SERVER_ERROR对应SDK错误码是LOGE_SERVER_BUSY和LOGE_INTERNAL_SERVER_ERROR，在后端语义重，是有超时和异常两种情况，没有办法更详细拆分

2024-12-25 06:36 UTC, linrunqi08 commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +        auto limiter = make_shared<ConcurrencyLimiter>(sName + "#quota#logstore#" + key, AppConfig::GetInstance()->GetSendRequestConcurrency(), 1);
15是dumin验证过性能比较好的参数，80的话，是我们对外文档中提到的最高数值。我们文档中对外说是1-50。所以最高80我觉得是比较合理的。太高的话，内存占用会升高

2024-12-25 06:36 UTC, linrunqi08 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +         LOG_INFO(sLogger,
已改成debug

2024-12-25 06:38 UTC, linrunqi08 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
>      lock_guard<mutex> lock(mLimiterMux);
这块对锁的粒度进行了细化，不会有两层锁的情况

2024-12-25 07:47 UTC, messixukejia approved these changes

2024-12-25 07:47 UTC, messixukejia commented on core/app_config/AppConfig.cpp
> +        mSendRequestConcurrency = mMinSendRequestConcurrency;
1

2024-12-25 07:47 UTC, messixukejia commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +    if (req) {
1

2024-12-27 07:57 UTC, yyuuttaaoo commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
>  bool ConcurrencyLimiter::IsValidToPop() {
always true？

2024-12-27 08:49 UTC, merged