Enhance Host Identification and Metadata Fetching in MachineInfoUtil
alibaba/loongcollector pull request #1989
Opened 2024-12-24 02:02 UTC by quzard

This pull request introduces several changes to the `MachineInfoUtil` module, focusing on enhancing the handling of host identification and metadata fetching. The key changes include the addition of new functions for serial number retrieval, improvements to the ECS metadata fetching process, and the introduction of a new host ID tag.

Enhancements to host identification:

* [`core/common/MachineInfoUtil.cpp`](diffhunk://#diff-b6a80d01ed9af129cd902f989e1b7e494daf57c84536cf87b3ecfbfd3beb25b2R506-R694): Added functions `GetSerialNumberFromEcsAssist`, `GetEcsAssistMachineIdFile`, `GetLocalHostId`, and `FetchHostId` to improve host identification and retrieval of the serial number from ECS assist.
* `core/constants/Constants.cpp`, `core/constants/Constants.h`: Introduced a new constant `LOG_RESERVED_KEY_HOSTID` for logging the host ID. [[1]](diffhunk://#diff-c79309e5937e003855cecc2303f30858c2e8481bb3f161282b29b4064bcaafd2R25) [[2]](diffhunk://#diff-499242abafc66bd1865b0718b04a0443e43708bafa526bcc0a4a19be0532f88bR26)
* [`core/plugin/processor/inner/ProcessorTagNative.cpp`](diffhunk://#diff-a40ad1204e0d6cc4774a6946a72ac2f8a9e90abad20b361c1270dc6632d23e26R32-R34): Added a feature to enable host ID tagging in logs when the `enable_host_id` flag is set. [[1]](diffhunk://#diff-a40ad1204e0d6cc4774a6946a72ac2f8a9e90abad20b361c1270dc6632d23e26R32-R34) [[2]](diffhunk://#diff-a40ad1204e0d6cc4774a6946a72ac2f8a9e90abad20b361c1270dc6632d23e26R76-R81)

Improvements to metadata fetching:

* [`core/common/MachineInfoUtil.cpp`](diffhunk://#diff-b6a80d01ed9af129cd902f989e1b7e494daf57c84536cf87b3ecfbfd3beb25b2R506-R694): Enhanced the `FetchECSMeta` function to include token-based authentication and improved error handling during metadata retrieval.

Code organization and cleanup:

* [`core/common/MachineInfoUtil.cpp`](diffhunk://#diff-b6a80d01ed9af129cd902f989e1b7e494daf57c84536cf87b3ecfbfd3beb25b2R18-R22): Added missing includes for `boost/filesystem.hpp` and `common/FileSystemUtil.h`. [[1]](diffhunk://#diff-b6a80d01ed9af129cd902f989e1b7e494daf57c84536cf87b3ecfbfd3beb25b2R18-R22) [[2]](diffhunk://#diff-b6a80d01ed9af129cd902f989e1b7e494daf57c84536cf87b3ecfbfd3beb25b2R48-R51)
* [`core/common/MachineInfoUtil.h`](diffhunk://#diff-f1cf29da300c6fb992aa30b70fb67263c2769e06884fc0766fd6a3a4a8eaf7a5L20-R22): Reorganized includes for `rapidjson` headers and added a declaration for the new `FetchHostId` function. [[1]](diffhunk://#diff-f1cf29da300c6fb992aa30b70fb67263c2769e06884fc0766fd6a3a4a8eaf7a5L20-R22) [[2]](diffhunk://#diff-f1cf29da300c6fb992aa30b70fb67263c2769e06884fc0766fd6a3a4a8eaf7a5R43)

2024-12-31 06:28 UTC, messixukejia requested changes

2024-12-31 06:28 UTC, messixukejia commented on core/application/Application.cpp
> +    appInfoJson["host_id"] = Json::Value(FetchHostId().hostId);
1

2024-12-31 06:28 UTC, messixukejia commented on core/plugin/processor/inner/ProcessorTagNative.cpp
> +#ifdef __ENTERPRISE__
del

2024-12-31 10:58 UTC, messixukejia commented on core/common/MachineInfoUtil.h
> +    std::mutex mutex;
变量命名

2024-12-31 10:58 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +                std::string mac;
因为已经变成了一直获取，就不用再用mac比较是否变化了

2024-12-31 10:58 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +    hostId = STRING_FLAG(agent_host_id);
机器组场景可以按照这个顺序

但是不能影响ecs的判断，agent_host_id不能影响entity结果

2024-12-31 13:06 UTC, messixukejia commented on core/common/MachineInfoUtil.h
> +    void SetECSMeta(const ECSMeta& meta) {
应该不涉及set，set是内部行为

2024-12-31 13:06 UTC, messixukejia commented on core/common/MachineInfoUtil.h
> +    const ECSMeta& GetECSMeta() {
ECSMeta加一个bool变量吧，表示是否ecs，降低外部判断复杂度

2024-12-31 13:06 UTC, messixukejia commented on core/common/MachineInfoUtil.h
> +        return mMetadata;
返回引用，这里加锁还有用吗？拿到之后用的时候，被改了，不也受影响？

2024-12-31 13:07 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +HostIdentifier::HostIdentifier() {
这个逻辑有ut吗

2024-12-31 13:12 UTC, quzard commented on core/common/MachineInfoUtil.h
> +    void SetECSMeta(const ECSMeta& meta) {
provider的更新线程会来更新SetECSMeta

2024-12-31 13:15 UTC, quzard commented on core/common/MachineInfoUtil.h
> +        return mMetadata;
因为会有线程来更新mMetadata。

不加锁是不是会有不同线程同时读写问题

2024-12-31 13:17 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +    mMetadata = GetECSMetaFromFile();
这里ecsmeta从无到有，hostid的取值也要跟着变，是不是没机会刷新了

2024-12-31 13:18 UTC, quzard commented on core/common/MachineInfoUtil.cpp
> +    mMetadata = GetECSMetaFromFile();
provider的线程里会修正

2024-12-31 23:52 UTC, messixukejia commented on pkg/logtail/libGoPluginAdapter.so
这里为什么也变更了？

2024-12-31 23:52 UTC, messixukejia commented on core/app_config/AppConfig.cpp
> +std::string GetAgentPrometheusAuthorizationPath() {
GetAgentGoLogConfDir、GetAgentPrometheusAuthorizationPath实现没什么差异，为什么要单独控制路径？

后续新增功能也不可能每次都增加特定目录

2024-12-31 23:52 UTC, messixukejia commented on core/plugin/flusher/sls/SLSClientManager.cpp
> +    const ECSMeta& ecsMetaCur = HostIdentifier::Instance()->GetECSMeta();
GetRunningEnvironment是初始化的时候调用一次，没有刷新的机会。
也得类似meta获取使用相同函数触发一次刷新。

另外ack deamonset场景，第一次一定是有空档期的？这个得考虑下怎么解决。

这个文件这次先不改吧，找太业再交流下后再修改

2024-12-31 23:52 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +std::string HostIdentifier::GetSerialNumberFromEcsAssist(const std::string& machineIdFile) {
HostIdentifier的函数实现 按照调用顺序 调排序吧，否则感觉有点乱

2024-12-31 23:52 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +ECSMeta HostIdentifier::FetchECSMeta() {
函数返回值不太适合直接返回结构体

2025-01-01 00:18 UTC, quzard commented on core/app_config/AppConfig.cpp
> +std::string GetAgentPrometheusAuthorizationPath() {
整体上还是历史上conf文件分布不集中导致。
未来对于新增的conf文件，需要统一放在AppConfig::GetInstance()->GetLoongcollectorConfDir()里。

2025-01-01 07:20 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +    static std::string hostId = CalculateRandomUUID();
成员变量

2025-01-01 07:23 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
外部用，入参引用&，内存由调用方管理。
内部的，指针 成员变量。避免产生拷贝。

2025-01-01 07:27 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +void HostIdentifier::UpdateHostId() {
UpdateHostId、updateecsmeta 原子，尽量快，不要有阻塞可能。


基于更新是一个单一线程、使用可能多线程这个大前提。

2025-01-01 07:54 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +    mMetadata = GetECSMetaFromFile();
开源差异。。

开源构造请求一次
商业版更新逻辑

2025-01-01 07:54 UTC, messixukejia commented on core/common/MachineInfoUtil.h
> +    const ECSMeta& GetECSMeta() {
关键对外接口使用注释

2025-01-01 07:54 UTC, messixukejia commented on core/monitor/Monitor.cpp
> +    ECSMeta ecsMeta = HostIdentifier::Instance()->GetECSMeta();
这个不是推荐做法，如果没用先删了吧

2025-01-01 08:57 UTC, yyuuttaaoo commented on core/common/MachineInfoUtil.cpp
> +    if (HostIdentifier::Instance()->FetchECSMeta(ecsMeta)) {
instance要调用构造，构造又调用instance，不会死锁吗

2025-01-01 09:08 UTC, messixukejia approved these changes

2025-01-01 09:57 UTC, yyuuttaaoo approved these changes

2025-01-01 13:46 UTC, merged