test: pipeline update unittest
alibaba/loongcollector pull request #1991
Opened 2024-12-24 08:04 UTC by Abingcbc

补充配置加载相关单测

2024-12-24 08:59 UTC, messixukejia requested changes

2024-12-24 08:59 UTC, messixukejia commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +#ifndef APSARA_UNIT_TEST_MAIN
宏在if外面，一个独立的块

2024-12-24 08:59 UTC, messixukejia commented on plugins/flusher/checker/flusher_checker.go
> +	return true
Block 存在的作用是什么

2024-12-24 08:59 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +    LOG_WARNING(sLogger, ("debug", "8"));
这种日志不要有了，即使是debug

2024-12-24 08:59 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +        LogtailPluginMock::GetInstance()->Start(GetConfigNameOfGoPipelineWithoutInput());
把APSARA_UNIT_TEST_MAIN的分支判断移到LogtailPlugin::GetInstance()内

尽量减少业务代码额外判断

2024-12-24 09:03 UTC, Abingcbc commented on plugins/flusher/checker/flusher_checker.go
> +	return true
最开始的go单测是假定flusher卡住，不符合实际input卡住，所以这里删除，移到input了。

2024-12-24 10:26 UTC, messixukejia commented on plugins/flusher/checker/flusher_checker.go
> +	return true
代码彻底删除

2024-12-25 02:10 UTC, Abingcbc commented on plugins/flusher/checker/flusher_checker.go
> +	return true
IsReady是flusher的接口定义，没法删，其他block的已删除

2024-12-25 03:31 UTC, messixukejia commented on plugins/flusher/checker/flusher_checker.go
> +	return true
Block这个字段

2024-12-26 05:47 UTC, messixukejia approved these changes

2024-12-26 05:47 UTC, messixukejia commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +    bool isProfileData = false;
尽量往下层

2024-12-27 03:58 UTC, henryzhx8 requested changes

2024-12-27 03:58 UTC, henryzhx8 commented on core/config/PipelineConfig.cpp
> +#endif
加上else，看下有没有其它办法

2024-12-27 03:58 UTC, henryzhx8 commented on core/monitor/profile_sender/ProfileSender.cpp
> +#ifndef APSARA_UNIT_TEST_MAIN
TODO

2024-12-27 03:58 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +                                "reason", "invalid flusher index or config update flusher from C++ to Go"));
这里应该不用改了吧

2024-12-27 03:58 UTC, henryzhx8 commented on core/pipeline/Pipeline.h
> +    const std::vector<std::unique_ptr<ProcessorInstance>>& GetProcessors() const { return mProcessorLine; }
ut用的直接friend

2024-12-27 03:58 UTC, henryzhx8 commented on core/pipeline/plugin/instance/ProcessorInstance.h
> +    const Processor* GetPlugin() const { return mPlugin.get(); }
同上

2024-12-27 03:58 UTC, henryzhx8 commented on core/runner/FlusherRunner.cpp
> +    ++mHttpSendingCnt;
格式化

2024-12-27 06:11 UTC, henryzhx8 requested changes

2024-12-27 06:11 UTC, henryzhx8 commented on core/unittest/plugin/PluginMock.h
> +const std::string InputFileMock2::sName = "input_file_mock2";
这种比较特殊的东西挪到相应的ut文件里

2024-12-27 06:11 UTC, henryzhx8 commented on core/unittest/plugin/PluginMock.h
> +    void Unblock() { mBlockFlag.store(false); }
都同意一下

2024-12-27 06:11 UTC, henryzhx8 commented on core/unittest/plugin/PluginMock.h
> +
挪到相应ut文件里

2024-12-27 06:11 UTC, henryzhx8 commented on core/unittest/plugin/PluginMock.h
> +const std::string FlusherSLSMock2::sName = "flusher_sls_mock2";
同上

2024-12-27 06:11 UTC, henryzhx8 commented on core/runner/sink/http/HttpSink.h
> +    bool AddRequest(std::unique_ptr<HttpSinkRequest>&& request);
参照ut意见

2024-12-30 02:00 UTC, henryzhx8 commented on core/runner/sink/http/HttpSink.cpp
> +bool HttpSink::AddRequest(std::unique_ptr<HttpSinkRequest>&& request) {
Stop那边也加上

2024-12-30 02:00 UTC, henryzhx8 commented on core/runner/sink/http/HttpSink.h
> +    bool AddRequest(std::unique_ptr<HttpSinkRequest>&& request);
这里加一句注释吧，是因为ut的原因需要额外override

2024-12-30 02:00 UTC, henryzhx8 commented on core/unittest/pipeline/HttpSinkMock.h
> +    }
UT里面都改用HttpSink，getinstance这里特殊处理

2024-12-30 02:00 UTC, henryzhx8 commented on core/unittest/pipeline/HttpSinkMock.h
> +                    }
这里删干净

2024-12-30 02:00 UTC, henryzhx8 commented on core/unittest/pipeline/HttpSinkMock.h
> +                static_cast<SLSSenderQueueItem*>(request->mItem)->mExactlyOnceCheckpoint = nullptr;
这行看下为什么需要

2024-12-30 06:29 UTC, henryzhx8 approved these changes

2024-12-30 07:14 UTC, merged