feat: prom support tls plaintext
alibaba/loongcollector pull request #2002
Opened 2024-12-31 03:09 UTC by catdogpandas

2024-12-31 07:18 UTC, messixukejia requested changes

2024-12-31 07:18 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +            string caFile = "/tmp/" + tmpJobName + "_ca.pem";
/tmp固定这种实现基本上都是不合理的

看上去整个实现从流程上不太合理，先评审下设计吧

2025-01-01 00:39 UTC, quzard requested changes

2025-01-01 00:39 UTC, quzard commented on core/prometheus/schedulers/ScrapeConfig.cpp
>  bool ScrapeConfig::InitTLSConfig(const Json::Value& tlsConfig) {
conf文件应该写在AppConfig::GetInstance()->GetLoongcollectorConfDir()这个目录里

2025-01-03 05:50 UTC, closed without merging