extend-http-dumper-ut-time
alibaba/loongcollector pull request #711
Opened 2023-03-16 02:14 UTC by EvanLjp

2023-03-16 02:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=711) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=711) before we can accept your contribution.<br/><hr/>**liujiapeng.ljp** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=711) it.</sub>

2023-03-21 01:54 UTC, messixukejia requested changes

2023-03-21 01:54 UTC, messixukejia commented on helper/dumper.go
> +	writeCounter *async.UnitTestCounterHelper
为什么要在正式代码关联测试的变量，有其他更合理的方法吗

2023-03-21 07:11 UTC, EvanLjp commented on helper/dumper.go
> +	writeCounter *async.UnitTestCounterHelper
没办法，异步控制，之前是时间控制，讯飞觉得不优雅，所以改的这个模式

2023-03-21 09:04 UTC, messixukejia approved these changes

2023-03-21 11:37 UTC, yyuuttaaoo approved these changes

2023-03-21 11:37 UTC, merged